List<Map<String, dynamic>> get testQuizzes => [
      {
        "question": "Who built the ark to survive the great flood?",
        "options": ["Abraham", "Moses", "Noah", "David"],
        "answerIndex": 2,
        "durationInSecs": 30,
        "answerExplanation": "",
      },
      {
        "question": "What is the first book of the Bible?",
        "options": ["Exodus", "Genesis", "Leviticus", "Numbers"],
        "answerIndex": 1,
        "durationInSecs": 30,
        "answerExplanation": "",
      },
      {
        "question": "Who was swallowed by a great fish?",
        "options": ["Elijah", "Jonah", "Job", "Daniel"],
        "answerIndex": 1,
        "durationInSecs": 30,
        "answerExplanation": "",
      },
      {
        "question": "Where was Jesus born?",
        "options": ["Nazareth", "Jerusalem", "Bethlehem", "Galilee"],
        "answerIndex": 2,
        "durationInSecs": 30,
        "answerExplanation": "",
      },
      {
        "question": "Who was the first king of Israel?",
        "options": ["David", "Saul", "Solomon", "Samuel"],
        "answerIndex": 1,
        "durationInSecs": 45,
        "answerExplanation": "",
      },
      {
        "question": "What was the name of the sea that Moses parted?",
        "options": [
          "Dead Sea",
          "Sea of Galilee",
          "Red Sea",
          "Mediterranean Sea"
        ],
        "answerIndex": 2,
        "durationInSecs": 45,
        "answerExplanation": "",
      },
      {
        "question": "Who betrayed Jesus for 30 pieces of silver?",
        "options": ["Peter", "Judas", "John", "Andrew"],
        "answerIndex": 1,
        "durationInSecs": 30,
        "answerExplanation": "",
      },
      {
        "question": "How many days did God take to create the world?",
        "options": ["5", "6", "7", "8"],
        "answerIndex": 1,
        "durationInSecs": 30,
        "answerExplanation": "",
      },
      {
        "question": "Who led the Israelites out of Egypt?",
        "options": ["Moses", "Aaron", "Joshua", "Caleb"],
        "answerIndex": 0,
        "durationInSecs": 30,
        "answerExplanation": "",
      },
      {
        "question": "What is the last book of the Bible?",
        "options": ["Revelation", "Jude", "Hebrews", "James"],
        "answerIndex": 0,
        "durationInSecs": 30,
        "answerExplanation": "",
      },
      {
        "question": "Who is known as the father of faith?",
        "options": ["Isaac", "Jacob", "Abraham", "Joseph"],
        "answerIndex": 2,
        "durationInSecs": 30,
        "answerExplanation": "",
      },
      {
        "question": "What was the first miracle Jesus performed?",
        "options": [
          "Healing a leper",
          "Turning water into wine",
          "Feeding 5,000",
          "Walking on water"
        ],
        "answerIndex": 1,
        "durationInSecs": 45,
        "answerExplanation": "",
      },
      {
        "question": "How many disciples did Jesus have?",
        "options": ["10", "11", "12", "13"],
        "answerIndex": 2,
        "durationInSecs": 30,
        "answerExplanation": "",
      },
      {
        "question": "What was the name of the garden where Adam and Eve lived?",
        "options": ["Eden", "Gethsemane", "Paradise", "Hebron"],
        "answerIndex": 0,
        "durationInSecs": 30,
        "answerExplanation": "",
      },
      {
        "question": "Who was thrown into the lion's den?",
        "options": ["Daniel", "Joseph", "Elijah", "Samuel"],
        "answerIndex": 0,
        "durationInSecs": 30,
        "answerExplanation": "",
      },
      {
        "question": "What was the name of Abraham's wife?",
        "options": ["Sarah", "Rebekah", "Leah", "Rachel"],
        "answerIndex": 0,
        "durationInSecs": 30,
        "answerExplanation": "",
      },
      {
        "question": "Who was the strongest man in the Bible?",
        "options": ["David", "Samson", "Goliath", "Solomon"],
        "answerIndex": 1,
        "durationInSecs": 30,
        "answerExplanation": "",
      },
      {
        "question": "How many plagues did God send on Egypt?",
        "options": ["7", "9", "10", "12"],
        "answerIndex": 2,
        "durationInSecs": 45,
        "answerExplanation": "",
      },
      {
        "question": "What did God give Moses on Mount Sinai?",
        "options": [
          "The Ark",
          "The Tabernacle",
          "The Ten Commandments",
          "The Covenant"
        ],
        "answerIndex": 2,
        "durationInSecs": 45,
        "answerExplanation": "",
      },
      {
        "question": "What was David's occupation before he became king?",
        "options": ["Shepherd", "Fisherman", "Carpenter", "Farmer"],
        "answerIndex": 0,
        "durationInSecs": 45,
        "answerExplanation": "",
      }
    ];
