// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB79lpHD9LyYySmTS4iuVoh89_B7JVVU4Y',
    appId: '1:182221656090:web:9ec9dc205e1a6299ad41a3',
    messagingSenderId: '182221656090',
    projectId: 'games-arena-dbc67',
    authDomain: 'games-arena-dbc67.firebaseapp.com',
    databaseURL: 'https://games-arena-dbc67-default-rtdb.firebaseio.com',
    storageBucket: 'games-arena-dbc67.firebasestorage.app',
    measurementId: 'G-ZY3PP8HB5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaOndcbXme8lQgYR57_THuKl3jFQw8VCI',
    appId: '1:182221656090:android:c5becf32fe20bb0cad41a3',
    messagingSenderId: '182221656090',
    projectId: 'games-arena-dbc67',
    databaseURL: 'https://games-arena-dbc67-default-rtdb.firebaseio.com',
    storageBucket: 'games-arena-dbc67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACVTudVydWnw829Wrr3zQzYDISMxot9DE',
    appId: '1:182221656090:ios:09cfd0a8ddbaafd0ad41a3',
    messagingSenderId: '182221656090',
    projectId: 'games-arena-dbc67',
    databaseURL: 'https://games-arena-dbc67-default-rtdb.firebaseio.com',
    storageBucket: 'games-arena-dbc67.firebasestorage.app',
    androidClientId:
        '182221656090-8eh6caa6b7vgesqviqfb7800l756165r.apps.googleusercontent.com',
    iosClientId:
        '182221656090-7pe7uevjqa9ick5udqnhgch2vt2rjvso.apps.googleusercontent.com',
    iosBundleId: 'com.hms.gamesarena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACVTudVydWnw829Wrr3zQzYDISMxot9DE',
    appId: '1:182221656090:ios:09cfd0a8ddbaafd0ad41a3',
    messagingSenderId: '182221656090',
    projectId: 'games-arena-dbc67',
    databaseURL: 'https://games-arena-dbc67-default-rtdb.firebaseio.com',
    storageBucket: 'games-arena-dbc67.firebasestorage.app',
    androidClientId:
        '182221656090-8eh6caa6b7vgesqviqfb7800l756165r.apps.googleusercontent.com',
    iosClientId:
        '182221656090-7pe7uevjqa9ick5udqnhgch2vt2rjvso.apps.googleusercontent.com',
    iosBundleId: 'com.hms.gamesarena',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB79lpHD9LyYySmTS4iuVoh89_B7JVVU4Y',
    appId: '1:182221656090:web:9ec9dc205e1a6299ad41a3',
    messagingSenderId: '182221656090',
    projectId: 'games-arena-dbc67',
    authDomain: 'games-arena-dbc67.firebaseapp.com',
    databaseURL: 'https://games-arena-dbc67-default-rtdb.firebaseio.com',
    storageBucket: 'games-arena-dbc67.firebasestorage.app',
    measurementId: 'G-ZY3PP8HB5S',
  );
}
